#!/usr/bin/env bash
# install nginx and change the default page
apt -y update
apt install -y nginx
echo "Holberton School" > /var/www/html/index.html
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlw\u4? permanent; }' /etc/nginx/sites-available/default

NOT_FOUND="\\\terror_page 404 /404.html;\n\
        location = /404.html {\n\
                root /var/www/html;\n\
                internal;\
        }"

sed -i '$NOT_FOUND' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
service nginx restart
