#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd

path="/etc/passwd"
while IFS=: read -r username group_id home_dir cmd userid passwd uid_info
do
	echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $cmd. $userid's place is protected by the passcode $passwd, more info about the user here: $uid_info"
done < $path
