#!/usr/bin/env bash
# This script is displaying "Holberton School" 9 times and "Hi" 1 time
i=1
while [ $i -le 10 ]
do
	if [ $i != 9 ]
	then
		echo "Holberton School"
	else
		echo "Hi"
	fi
	(( i++ ))
done
